Actions: Remove --no-index from Wheel test build command (#424)
This is a fix for:


https://github.com/MHKiT-Software/MHKiT-Python/actions/runs/18594536347/job/53017269068#step:6:14

```
Run pip install 'mhkit[all]' --no-index --find-links dist/
Looking in links: dist/
Processing ./dist/mhkit-1.0.1-py3-none-any.whl
INFO: pip is looking at multiple versions of mhkit[all] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement numpy>=2.0.0 (from mhkit[all]) (from versions: none)
ERROR: No matching distribution found for numpy>=2.0.0
Error: Process completed with exit code 1.
```

This fix removes `--no-index` which caused pip to only use local
packages, which causes the above failure for any/all external
packages/modules.